In [2]:
from pyspark.sql import SparkSession
from pyspark.sql.types import *
from pyspark.sql import functions as F
from pyspark.sql import Window

# Create SparkSession
spark = (SparkSession.builder
                    .appName('PySparkSyntax')
                    .getOrCreate()
        )

# Define the schema for a DataFrame
schema = StructType([
    StructField("name", StringType(), True),
    StructField("age", IntegerType(), True),
    StructField("city", StringType(), True)
])


# Create a DataFrame using the schema
data = [("Alice", 25, "New York"), ("Bob", 30, "San Francisco"), ("Charlie", 35, "Chicago")]
df = spark.createDataFrame(data, schema)

spark.sparkContext.setLogLevel("WARN") # INFO WARN ERROR DEBUG ALL

# Show the DataFrame
df.show()

+-------+---+-------------+
|   name|age|         city|
+-------+---+-------------+
|  Alice| 25|     New York|
|    Bob| 30|San Francisco|
|Charlie| 35|      Chicago|
+-------+---+-------------+

In [3]:
df.columns

['name', 'age', 'city']

In [4]:
# Creating a new column called 'new_age'
df = df.withColumn('new_age', (F.col('age') + 5).cast('int'))
df.toPandas()

      name  age           city  new_age
0    Alice   25       New York       30
1      Bob   30  San Francisco       35
2  Charlie   35        Chicago       40

In [5]:
# Replacing a existing new column called 'new_age' with new values
df = df.withColumn('new_age', df.new_age + 2)
df.toPandas()

      name  age           city  new_age
0    Alice   25       New York       32
1      Bob   30  San Francisco       37
2  Charlie   35        Chicago       42

In [6]:
df = df.withColumn('constant', F.lit('TableA'))
df.toPandas()

      name  age           city  new_age constant
0    Alice   25       New York       32   TableA
1      Bob   30  San Francisco       37   TableA
2  Charlie   35        Chicago       42   TableA

In [7]:
df = df.withColumnRenamed('new_age', 'new_age2')
df.toPandas()

      name  age           city  new_age2 constant
0    Alice   25       New York        32   TableA
1      Bob   30  San Francisco        37   TableA
2  Charlie   35        Chicago        42   TableA

In [8]:
df = df.withColumnRenamed('new_age3', 'new_age4')
df.toPandas()

      name  age           city  new_age2 constant
0    Alice   25       New York        32   TableA
1      Bob   30  San Francisco        37   TableA
2  Charlie   35        Chicago        42   TableA

In [9]:
df = df.select(F.col('name').alias('FirstName')
                ,F.col('age')
                ,F.col('city')
              )

df.toPandas()

  FirstName  age           city
0     Alice   25       New York
1       Bob   30  San Francisco
2   Charlie   35        Chicago

In [10]:
df = df.drop('city')
df.toPandas()

  FirstName  age
0     Alice   25
1       Bob   30
2   Charlie   35

In [11]:
df = df.drop('new_age99')
df.toPandas()

  FirstName  age
0     Alice   25
1       Bob   30
2   Charlie   35

In [12]:
df = df.select('FirstName', 'age')

df.toPandas()

  FirstName  age
0     Alice   25
1       Bob   30
2   Charlie   35

In [13]:
df_select = df.selectExpr('FirstName as Name', 'age as Age', 'age*2 as DoubleAge')
df_select.toPandas()

      Name  Age  DoubleAge
0    Alice   25         50
1      Bob   30         60
2  Charlie   35         70

In [14]:
spark.stop()